services:
  - type: web
    name: votes-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: votes-db
          property: connectionString
      - key: ADMIN_PASSWORD
        value: change-moi
databases:
  - name: votes-db
    plan: free
